version: '3.3'
volumes:
  data:
services:
  db:
    image: mysql:5.6
    ports:
      - "3310:3310"
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=scadabpms